function [returnCode] = setVREPTopics(robot)
%SETVREPTOPICS sets the list of implemented topics and their types for the 
%simulated robot.
%
%   [returnCode] = setVREPTopics(robot)
%
%   'returnCode' will always set to '0' (no errors).

% -------------------------------------------------------------------------
% Ivan Fernandez-Vega
% B.Sc. Degree in Computer Engineering
% University of Malaga
% June, 2016
% -------------------------------------------------------------------------
%    This program is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    This program is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with this program.  If not, see <http://www.gnu.org/licenses/>.
% -------------------------------------------------------------------------

    % List of topics
    topics = ['/arm_1_joint/command                ';...    % 1
              '/arm_2_joint/command                ';...
              '/arm_3_joint/command                ';...
              '/arm_4_joint/command                ';...
              '/arm_5_joint/command                ';...    % 5
              '/camera/depth/image                 ';...
              '/camera/depth/image/compressed      ';...
              '/camera/rgb/image_color             ';...
              '/camera/rgb/image_color/compressed  ';...
              '/camera/rgb/image_mono              ';...    % 10
              '/camera/rgb/image_mono/compressed   ';...
              '/gripper_1_joint/command            ';...
              '/mobile_base/commands/led1          ';...
              '/mobile_base/commands/led2          ';...
              '/mobile_base/commands/motor_power   ';...    % 15
              '/mobile_base/commands/reset_odometry';...
              '/mobile_base/commands/velocity      ';...
              '/mobile_base/controller_info        ';...
              '/mobile_base/events/bumper          ';...
              '/mobile_base/events/button          ';...    % 20
              '/mobile_base/events/cliff           ';...
              '/mobile_base/events/wheel_drop      ';...
              '/mobile_base/sensors/core           ';...
              '/mobile_base/sensors/imu_data       ';...
              '/mobile_base/sensors/imu_data_raw   ';...    % 25
              '/mobile_base/version_info           ';...
              '/odom                               '];      % 27
   
     % List of types     
     types = ['std_msgs/Float64                    ';...    % 1
              'std_msgs/Float64                    ';...
              'std_msgs/Float64                    ';...
              'std_msgs/Float64                    ';...
              'std_msgs/Float64                    ';...    % 5
              'sensor_msgs/image                   ';...
              'sensor_msgs/compressed image        ';...
              'sensor_msgs/image                   ';...
              'sensor_msgs/compressed image        ';...
              'sensor_msgs/image                   ';...    % 10
              'sensor_msgs/compressed image        ';...
              'std_msgs/Float64                    ';...
              'kobuki_msgs/Led                     ';...
              'kobuki_msgs/Led                     ';...
              'kobuki_msgs/MotorPower              ';...    % 15
              'std_msgs/Empty                      ';...
              'geometry_msgs/Twist                 ';...
              'kobuki_msgs/ControllerInfo          ';...
              'kobuki_msgs/BumperEvent             ';...
              'kobuki_msgs/ButtonEvent             ';...    % 20
              'kobuki_msgs/CliffEvent              ';...
              'kobuki_msgs/WheelDropEvent          ';...
              'kobuki_msgs/SensorState             ';...
              'sensor_msgs/imu                     ';...
              'sensor_msgs/imu                     ';...    % 25
              'kobuki_msgs/VersionInfo             ';...
              'nav_msgs/Odometry                   '];      % 27
    
    % Setting the robot's topics and types
    robot.v_topics        = cellstr(topics);
    robot.v_topics_types  = cellstr(types);
    
    % No errors
    returnCode = 0;
end